INSERT INTO users (id, name, age) VALUES (1, "Lil Bub", 27);
INSERT INTO users (id, name, age) VALUES (2, "Maru", 27);
INSERT INTO users (id, name, age) VALUES (3, "Lassie", 27);
INSERT INTO users (id, name, age) VALUES (4, "Jim", 27);
INSERT INTO users (id, name, age) VALUES (5, "Lil Foot", 27);
INSERT INTO users (id, name, age) VALUES (6, "Lil Pete", 27);
INSERT INTO users (id, name, age) VALUES (7, "Lil Wayne", 27);
INSERT INTO users (id, name, age) VALUES (8, "T Rex", 27);
INSERT INTO users (id, name, age) VALUES (9, "Lil B", 27);
INSERT INTO users (id, name, age) VALUES (10, "Boosie", 27);
INSERT INTO users (id, name, age) VALUES (11, "Young Thug", 27);
INSERT INTO users (id, name, age) VALUES (12, "YG", 27);
INSERT INTO users (id, name, age) VALUES (13, "Bird Man", 27);
INSERT INTO users (id, name, age) VALUES (14, "Lil Flip", 27);
INSERT INTO users (id, name, age) VALUES (15, "Paul Wall", 27);
INSERT INTO users (id, name, age) VALUES (16, "Chamillionaire", 27);
INSERT INTO users (id, name, age) VALUES (17, "2 Chainz", 27);
INSERT INTO users (id, name, age) VALUES (18, "Lil Waka Flocka Bub", 27);
INSERT INTO users (id, name, age) VALUES (19, "Pusha T", 27);
INSERT INTO users (id, name, age) VALUES (20, "Too Short", 27);


INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "Bombs Over Baghdad", "hip hop", 27, "3/1", "");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "ATLiens", "hip hop", 27, "5/1", "6/1");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "Game Over", "hip hop", 27, "2/1", "3/1");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "Stankonia", "hip hop", 27, "1/1", "2/1");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "Speakerbox", "hip hop", 27, "3/11", "4/11");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "Illmatic", "hip hop", 27, "5/13", "6/13");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "All Eyez On Me", "hip hop", 27, "3/2", "4/2");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "Prototype", "hip hop", 27, "3/21", "4/6");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "The Score", "hip hop", 27, "7/1", "8/1");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "White Album", "hip hop", 27, "9/1", "10/1");

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29, 10, "user 1", "project 1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30, 10, "user 1", "project 1");
